### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by epikindynos**

### CODE REVIEW

**Comment by epikindynos** [comment]
@quest-bot loot #36

**Review by karaderpino — CHANGES_REQUESTED** [review]
change me

**Review by karaderpino — APPROVED** [review]

**Comment by epikindynos** [comment]
@quest-bot-dev loot #46

**Comment by epikindynos** [comment]
@quest-bot-dev look #42

**Comment by epikindynos** [comment]
@quest-bot-dev loot #42

**Pull request merged**
