### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by epikindynos**

### CODE REVIEW

**Comment by epikindynos** [comment]
@quest-bot-dev loot #42 #43

**Comment by epikindynos** [comment]
@quest-bot-dev otinanaire

**Comment by epikindynos** [comment]
@quest-bot-dev look otinanai

**Comment by epikindynos** [comment]
@quest-bot-dev loot #46

**Comment by karaderpino** [comment]
@quest-bot-dev stash 100

**Comment by karaderpino** [comment]
@quest-bot-dev restash 100

**Comment by karaderpino** [comment]
@quest-bot-dev reward @epikindynos

**Comment by karaderpino** [comment]
@quine-bot-dev abort #46

**Comment by karaderpino** [comment]
@quest-bot-dev abort #46

**Comment by karaderpino** [comment]
@quest-bot-dev embark

**Comment by epikindynos** [comment]
@quest-bot-dev reward @epikindynos

**Comment by karaderpino** [comment]
@quest-bot-dev loot #46

**Comment by karaderpino** [comment]
@quest-bot-dev loot #42

**Comment by epikindynos** [comment]
@quest-bot-dev loot #42

**Pull request closed without merging**
